# Generated by Django 4.2.1 on 2023-06-03 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c021bb73-7be6-4a1f-be93-494013bbf7ad'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступність')),
                ('image', models.ImageField(upload_to='product_image', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'db_table': 'product',
            },
        ),
    ]
