# Generated by Django 4.2.1 on 2023-06-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=50, verbose_name='Категорія'),
            preserve_default=False,
        ),
    ]
