# Generated by Django 4.2.1 on 2023-06-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_is_available_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True, verbose_name='Знижка'),
        ),
    ]
