# Generated by Django 4.2.1 on 2023-06-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='vegetable', max_length=50, verbose_name='Категорія'),
        ),
    ]
