# Generated by Django 4.2.1 on 2023-06-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='category_image', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
