# Generated by Django 4.2.1 on 2023-06-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category_image', null=False, verbose_name='Фото'),
        ),
    ]
